name: CI Процесс

on:
  push:
    branches: [develop, release/*, main]
  pull_request:
    branches: [develop, release/*, main]


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: JDK 17 тохируулах
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkstyle шалгах
        run: mvn checkstyle:check

      - name: JUnit тест ба JaCoCo coverage шалгах
        run: mvn test jacoco:check

      - name: JaCoCo тайлан үүсгэх
        run: mvn jacoco:report
